server:
  port: 7002
spring:
  profiles:
    active: @profile.active@
  application:
    name: mq-hothatch-adapter
logging:
  path: /data/logs/${spring.application.name}
mybatis:
  mapper-locations: classpath:com/hiersun/adapter/mapper/*.xml
