spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.7.125:3306/message?useUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&allowMultiQueries=true
      username: o2ouser
      password: ydprzuo2&5fdKG2i
      max-active: 100
      min-idle: 5
      initial-size: 5
      max-wait: 10000
      validation-query: select 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.7.126:8761/eureka/,http://192.168.7.113:8761/eureka/